"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import {
  CRITERIA,
  DEFAULT_ANSWERS,
  DEFAULT_WEIGHTS,
  PATHWAYS,
  PROFILE_QUESTIONS,
  rankPathways,
  type Answers,
  type CriterionKey,
  type PathwayId,
  type Weights,
} from "@/app/decide/pathways";

type Metric = {
  part_number: string;
  title: string;
  section_count: number;
  requirement_count: number;
  first_subpart_code: string | null;
  definitions_section_code: string | null;
};

const WEIGHT_LABELS = ["Ignore", "Minor", "Some", "Important", "High", "Critical"];

export function DecisionWizard({ metrics }: { metrics: Metric[] }) {
  const [answers, setAnswers] = useState<Answers>(DEFAULT_ANSWERS);
  const [weights, setWeights] = useState<Weights>(DEFAULT_WEIGHTS);
  const [saveState, setSaveState] = useState<"idle" | "saving" | "saved">("idle");

  const metricById = useMemo(() => {
    const m = new Map<string, Metric>();
    for (const x of metrics) m.set(x.part_number, x);
    return m;
  }, [metrics]);

  const result = useMemo(() => rankPathways(answers, weights), [answers, weights]);
  const top = result.ranked[0];
  const hasPriorities = result.totalWeight > 0;

  function densityLine(id: PathwayId): string | null {
    const m = metricById.get(id);
    if (!m || !m.section_count) return null;
    const density = (m.requirement_count / m.section_count).toFixed(1);
    return `${m.section_count} sections · ${m.requirement_count.toLocaleString()} requirements · ${density} per section`;
  }

  async function saveToNotes() {
    if (!top) return;
    setSaveState("saving");
    const lines: string[] = [];
    lines.push("Pathway decision analysis (generated by the decision guide)\n");
    lines.push("Project profile:");
    for (const q of PROFILE_QUESTIONS) {
      const opt = q.options.find((o) => o.value === answers[q.key]);
      lines.push(`  - ${q.label}: ${opt?.label ?? answers[q.key]}`);
    }
    lines.push("\nPriorities (0–5):");
    for (const c of CRITERIA) lines.push(`  - ${c.label}: ${weights[c.key]}`);
    lines.push("\nResult:");
    result.ranked.forEach((r, i) => {
      lines.push(`  ${i + 1}. ${r.pathway.name} — ${r.pct}%${i === 0 ? "  (recommended)" : ""}`);
    });
    for (const r of result.ineligible) {
      lines.push(`  — ${r.pathway.name}: ineligible (${r.ineligibleReason})`);
    }
    if (top.caveats.length) {
      lines.push("\nCaveats:");
      for (const cav of top.caveats) lines.push(`  - ${cav}`);
    }
    if (top.pathway.levers.length) {
      lines.push(`\nReview-time levers (${top.pathway.name}):`);
      for (const lev of top.pathway.levers) lines.push(`  - ${lev.label}: ${lev.detail}`);
    }
    try {
      await fetch("/api/notes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ kind: "decision", code: `${top.pathway.name} pathway`, body: lines.join("\n") }),
      });
      setSaveState("saved");
    } catch {
      setSaveState("idle");
    }
  }

  return (
    <div className="space-y-8">
      {/* 1. Project profile (gating) */}
      <section className="rounded-lg border border-slate-200 bg-white p-6">
        <h2 className="text-lg font-semibold">1. Your project</h2>
        <p className="mt-1 text-sm text-slate-600">
          These answers narrow the feasible pathways and tune the scoring.
        </p>
        <div className="mt-4 space-y-5">
          {PROFILE_QUESTIONS.map((q) => (
            <div key={q.key}>
              <div className="text-sm font-medium text-ink">{q.label}</div>
              <div className="text-xs text-slate-500">{q.help}</div>
              <div className="mt-2 flex flex-wrap gap-2">
                {q.options.map((opt) => {
                  const active = answers[q.key] === opt.value;
                  return (
                    <button
                      key={opt.value}
                      onClick={() => {
                        setAnswers((a) => ({ ...a, [q.key]: opt.value }));
                        setSaveState("idle");
                      }}
                      className={`rounded-full border px-3 py-1.5 text-sm transition ${
                        active
                          ? "border-accent bg-accent text-white"
                          : "border-slate-300 bg-white text-slate-700 hover:border-accent"
                      }`}
                    >
                      {opt.label}
                    </button>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 2. Priorities (weights) */}
      <section className="rounded-lg border border-slate-200 bg-white p-6">
        <h2 className="text-lg font-semibold">2. Your priorities</h2>
        <p className="mt-1 text-sm text-slate-600">
          Weight what matters for your project. The recommendation updates live.
        </p>
        <div className="mt-4 space-y-4">
          {CRITERIA.map((c) => (
            <div key={c.key} className="grid grid-cols-1 gap-1 sm:grid-cols-[1fr_auto]">
              <div>
                <label htmlFor={`w-${c.key}`} className="text-sm font-medium text-ink">
                  {c.label}
                </label>
                <div className="text-xs text-slate-500">{c.help}</div>
              </div>
              <div className="flex items-center gap-3 sm:w-64">
                <input
                  id={`w-${c.key}`}
                  type="range"
                  min={0}
                  max={5}
                  value={weights[c.key]}
                  onChange={(e) => {
                    const v = Number(e.target.value);
                    setWeights((w) => ({ ...w, [c.key]: v }));
                    setSaveState("idle");
                  }}
                  className="flex-1 accent-accent"
                />
                <span className="w-16 shrink-0 text-right text-xs font-medium text-slate-600">
                  {WEIGHT_LABELS[weights[c.key]]}
                </span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 3. Recommendation */}
      <section className="rounded-lg border border-slate-200 bg-white p-6">
        <h2 className="text-lg font-semibold">3. Recommendation</h2>
        {!hasPriorities ? (
          <p className="mt-2 text-sm text-slate-500">
            Set at least one priority above “Ignore” to rank the pathways.
          </p>
        ) : (
          <>
            <div className="mt-4 space-y-3">
              {result.ranked.map((r, i) => (
                <div key={r.id}>
                  <div className="flex items-baseline justify-between text-sm">
                    <span className="font-medium text-ink">
                      {i === 0 && (
                        <span className="mr-2 rounded bg-accent px-2 py-0.5 text-xs font-semibold uppercase tracking-wide text-white">
                          Top match
                        </span>
                      )}
                      10 CFR {r.pathway.name} — {r.pathway.tagline}
                    </span>
                    <span className="tabular-nums font-semibold text-slate-700">{r.pct}%</span>
                  </div>
                  <div className="mt-1 h-2.5 w-full overflow-hidden rounded-full bg-slate-100">
                    <div
                      className={`h-full rounded-full ${i === 0 ? "bg-accent" : "bg-slate-400"}`}
                      style={{ width: `${r.pct}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>

            {top && (
              <div className="mt-6 rounded-lg border border-slate-200 bg-slate-50 p-4">
                <h3 className="text-sm font-semibold text-ink">
                  Why 10 CFR {top.pathway.name} leads, given your priorities
                </h3>
                {densityLine(top.id) && (
                  <p className="mt-1 text-xs text-slate-500">From the loaded text: {densityLine(top.id)}.</p>
                )}
                <ul className="mt-3 space-y-2">
                  {CRITERIA.filter((c) => weights[c.key] > 0)
                    .sort((a, b) => weights[b.key] * top.scores[b.key] - weights[a.key] * top.scores[a.key])
                    .map((c) => (
                      <li key={c.key} className="text-sm text-slate-700">
                        <span className="font-medium text-ink">{c.label}</span>{" "}
                        <span className="text-xs text-slate-400">
                          ({top.scores[c.key]}/5 × {WEIGHT_LABELS[weights[c.key]].toLowerCase()})
                        </span>
                        <div className="text-sm text-slate-600">{top.pathway.why[c.key as CriterionKey]}</div>
                      </li>
                    ))}
                </ul>
                {top.caveats.length > 0 && (
                  <div className="mt-3 rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">
                    {top.caveats.map((cav, k) => (
                      <p key={k}>⚠ {cav}</p>
                    ))}
                  </div>
                )}
                <Citations id={top.id} metricById={metricById} />
              </div>
            )}

            {result.ranked.length > 0 && (
              <div className="mt-6">
                <h3 className="text-sm font-semibold text-ink">Opportunities to compress review time</h3>
                <p className="mt-1 text-xs text-slate-500">
                  Provisions that front-load or shorten NRC review, by pathway (ranked as above). These back the
                  “Schedule predictability” score — the regulations set process, not durations.
                </p>
                <div className="mt-3 space-y-3">
                  {result.ranked.map((r) => (
                    <div key={r.id} className="rounded border border-slate-200 bg-white p-3">
                      <div className="text-sm font-medium text-ink">
                        10 CFR {r.pathway.name}
                        {r.id === top?.id && (
                          <span className="ml-2 rounded bg-slate-100 px-1.5 py-0.5 text-[10px] uppercase tracking-wide text-slate-500">
                            recommended
                          </span>
                        )}
                      </div>
                      <ul className="mt-1 space-y-1">
                        {r.pathway.levers.map((lev, i) => (
                          <li key={i} className="text-sm text-slate-600">
                            {lev.href ? (
                              <Link href={lev.href} className="font-medium xref-link">
                                {lev.label}
                              </Link>
                            ) : (
                              <span className="font-medium text-slate-700">{lev.label}</span>
                            )}{" "}
                            — {lev.detail}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {result.ineligible.length > 0 && (
              <div className="mt-4 text-sm text-slate-500">
                {result.ineligible.map((r) => (
                  <p key={r.id}>
                    <span className="font-medium line-through">10 CFR {r.pathway.name}</span> — ruled out:{" "}
                    {r.ineligibleReason}
                  </p>
                ))}
              </div>
            )}

            <div className="mt-6 flex items-center gap-3">
              <button
                onClick={saveToNotes}
                disabled={saveState === "saving" || !top}
                className="rounded bg-accent px-3 py-1.5 text-sm text-white disabled:opacity-50"
              >
                {saveState === "saving" ? "Saving…" : saveState === "saved" ? "Saved to notes ✓" : "Save analysis to notes"}
              </button>
              {saveState === "saved" && (
                <Link href="/notes" className="text-sm xref-link">
                  View in notes →
                </Link>
              )}
            </div>
          </>
        )}
      </section>

      <p className="text-xs text-slate-400">
        This guide is a structured starting point, not legal or regulatory advice. The scores are
        adjustable judgments; confirm eligibility and requirements against the governing regulations and
        current NRC guidance.
      </p>
    </div>
  );
}

function Citations({ id, metricById }: { id: PathwayId; metricById: Map<string, Metric> }) {
  const pathway = PATHWAYS.find((p) => p.id === id)!;
  const m = metricById.get(id);
  return (
    <div className="mt-4 flex flex-wrap gap-4 border-t border-slate-200 pt-3 text-sm">
      {m?.first_subpart_code && (
        <Link href={`/part/${id}/${m.first_subpart_code}`} className="xref-link">
          Explore 10 CFR {pathway.name} →
        </Link>
      )}
      {m?.definitions_section_code && (
        <Link href={`/section/${m.definitions_section_code}`} className="xref-link">
          Key definitions (§ {m.definitions_section_code}) →
        </Link>
      )}
    </div>
  );
}
